version: "3.8"

services:
  db:
    image: postgres:15-alpine

    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: taskwriter
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "python -m pip install psycopg2 && gunicorn taskWriter.wsgi:application -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
