# Generated by Django 5.1.3 on 2024-11-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskWriter', '0002_filemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='path',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='Image',
            field=models.ImageField(default='image.jfif', upload_to='media/'),
        ),
    ]
