# Generated by Django 5.1.3 on 2024-11-23 01:04

import taskWriter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskWriter', '0003_remove_filemodel_path_filemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='Image',
            field=models.ImageField(default='image.jfif', upload_to=taskWriter.models.upload_to, verbose_name='Image'),
        ),
    ]
